import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Fleet } from "./fleet.ts";
import { taskDir, turnEndPath } from "./task.ts";

/**
 * Turn-end hook (kernel plan v1, M1-P4 step 3; R-082b, PR-209).
 *
 * The hook is a generated script in the TASK directory (never inside the
 * worktree, FM-059) that the executor invokes when the payload command
 * exits. It writes tasks/<id>/turn-end as JSON:
 *
 *   {"endedAt": "<ISO-8601>", "exitCode": <number>}
 *
 * That file is the M1-P5 watcher's wake signal. It is a notification,
 * not the task's state: meta.json status plus this exit code together
 * are the single current-state authority (plan constraint C-1), and a
 * MISSING turn-end file never means success (tuition T-002: an agent
 * that dies quietly leaves no turn-end and a dirty worktree).
 *
 * The hook takes the payload's exit code as its single argument, so any
 * adapter (the M1 subprocess adapter, and the window or cloud-session
 * adapters of the M4 era) can invoke it without knowing anything else
 * about the task. It is written with the .mjs extension so it parses as
 * ESM regardless of the nearest package.json, since it runs inside the
 * fleet home rather than inside this package.
 */

/** The generated hook script for a task. */
export function turnEndHookPath(fleet: Fleet, taskId: string): string {
  return join(taskDir(fleet, taskId), "turn-end-hook.mjs");
}

/**
 * Generate the hook script. The turn-end path is baked in as a literal,
 * so the hook needs no fleet resolution and no environment at all.
 */
export function renderTurnEndHook(turnEndFile: string): string {
  return `#!/usr/bin/env node
// Generated by tiphys spawn (kernel plan v1, M1-P4 step 3). Invoked by the
// executor adapter when the payload command exits, with the payload's exit
// code as its single argument. Writes the turn-end record the M1-P5 watcher
// wakes on. Do not edit: spawn regenerates it.
import { writeFileSync } from "node:fs";

const exitCode = Number(process.argv[2]);
if (!Number.isInteger(exitCode)) {
  process.stderr.write(
    "tiphys turn-end hook: expected one integer exit-code argument\\n",
  );
  process.exit(64);
}
writeFileSync(
  ${JSON.stringify(turnEndFile)},
  \`\${JSON.stringify({ endedAt: new Date().toISOString(), exitCode }, null, 2)}\\n\`,
);
`;
}

/** Write the hook for a task and return its path. */
export function writeTurnEndHook(fleet: Fleet, taskId: string): string {
  const path = turnEndHookPath(fleet, taskId);
  writeFileSync(path, renderTurnEndHook(turnEndPath(fleet, taskId)), {
    mode: 0o755,
  });
  return path;
}
